<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Positibe\Bundle\NewsBundle\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;

/**
 * Class CommentFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 */
class CommentFormType extends AbstractType
{
    /** @var  AuthorizationChecker */
    protected $authorizationChecker;

    public function __construct(AuthorizationChecker $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'name',
                null,
                array(
                    'label' => 'post_comment.form.name_label',
                )
            )
            ->add(
                'email',
                null,
                array(
                    'label' => 'post_comment.form.email_label',
                )
            )
            ->add(
                'url',
                null,
                array(
                    'label' => 'post_comment.form.url_label',
                )
            )
            ->add(
                'message',
                null,
                array(
                    'label' => 'post_comment.form.message_label',
                )
            );

        if ($this->authorizationChecker->isGranted('ROLE_MODERATOR')) {
            $builder->add(
                'status',
                ChoiceType::class,
                array(
                    'label' => 'post_comment.form.status_label',
                    'choices' => Comment::getStatusList(),
                )
            );
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Comment',
            )
        );
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'positibe_post_comment';
    }
}
