<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\NewsBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class TagFormType
 * @package Positibe\Bundle\NewsBundle\Form\Type
 */
class TagFormType extends AbstractType
{
    private $locales;

    public function __construct($locales)
    {
        $this->locales = $locales;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'name',
                null,
                array(
                    'label' => 'post_tag.form.name_label',
                )
            );
        if ($options['data'] !== null && $options['data']->getId()) {
            $builder->add(
                'locale',
                ChoiceType::class,
                array(
                    'label' => 'post_tag.form.locale_label',
                    'choices' => array_combine($this->locales, $this->locales),
                )
            );
        };
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\NewsBundle\Entity\Tag',
            )
        );
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'positibe_post_tag';
    }
}
